dependencies:
  pre:
    - sudo pip install -U crcmod
  post:
    - ./gradlew :app:assembleDebug -PdisablePreDex
    - ./gradlew :app:assembleDebugTest -PdisablePreDex
    - echo $GCLOUD_SERVICE_KEY | base64
    - sudo /opt/google-cloud-sdk/bin/gcloud config set project percolatetest-40ba0-195015
    - sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update
    - sudo /opt/google-cloud-sdk/bin/gcloud --quiet components install beta
    - sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account steve-account@percolatetest-40ba0-195015.iam.gserviceaccount.com --key-file ${HOME}/client-secret.json