# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      ADB_INSTALL_TIMEOUT: 10
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew clean androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Install Android dependencies
          command: |
            sdkmanager "platform-tools"
            sdkmanager "platforms;android-25"
            sdkmanager "build-tools;24.0.3"
            sdkmanager "extras;android;m2repository"
            sdkmanager "extras;google;m2repository"
            sdkmanager "system-images;android-21;default;armeabi-v7a"


